### ISSUE TITLE
Modules fail to load

### ISSUE THREAD

**Issue by DigiAngel** [darkoperator/Posh-NVS#2]
This is on a fresh install of Windows 7:

```
PS C:\Windows\system32> Import-Module posh-nessus -Verbose -Force
Import-Module : The specified module 'posh-nessus' was not loaded because no valid module file was found in any module
directory.
At line:1 char:14
+ Import-Module <<<<  posh-nessus -Verbose -Force
    + CategoryInfo          : ResourceUnavailable: (posh-nessus:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I've copied everything into the Modules dir.  Thank you

**Comment by darkoperator** [comment]
Could it be that the module is Posh-NVS and not Posh-Nessus? so you need to do import-module posh-nfs -verbose -force

**Comment by DigiAngel** [comment]
Well hrmmm...I tried posh-nvs:

```
PS C:\users\James\Downloads\Posh-NVS-master> Import-Module posh-nvs -Verbose -Force
Import-Module : The specified module 'posh-nvs' was not loaded because no valid module file was found in any module dir
ectory.
At line:1 char:14
+ Import-Module <<<<  posh-nvs -Verbose -Force
    + CategoryInfo          : ResourceUnavailable: (posh-nvs:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

the command

```
Import-Module posh-nessus -Verbose -Force
```

is from the README.MD.  Thank you.

**Comment by darkoperator** [comment]
You do know this module is for version 5 right? Version 6 of nessus is not supported by it. In your module path variable for PowerShell 4.0/5.0 do you have the path to where it was installed in your my documents? Have you tried loading it specifying the full path to the installation folder to test?

**Comment by DigiAngel** [comment]
Yugh...ya I'm needing version 6....thanks Carlos I'll close this out.

**Comment by darkoperator** [comment]
Just tried it by hand and it worked, can you confirm you are specifying the right folder or manifest file name 

PS C:\Users\Carlos> cd .\Downloads\
PS C:\Users\Carlos\Downloads> Unblock-File .\Posh-NVS-master.zip
PS C:\Users\Carlos\Downloads> cd .\Posh-NVS-master\
PS C:\Users\Carlos\Downloads\Posh-NVS-master> ls

```
Directory: C:\Users\Carlos\Downloads\Posh-NVS-master
```

Mode                LastWriteTime         Length Name

---

d-----       12/16/2015   2:27 PM                Assembly
d-----       12/16/2015   2:27 PM                en-US
d-----       12/16/2015   2:27 PM                nessus-sharp
------        3/10/2014   9:11 PM          52136 policy.psm1
------        3/10/2014   9:11 PM           5688 Posh-NVS.psd1
------        3/10/2014   9:11 PM          72793 Posh-NVS.psm1
------        3/10/2014   9:11 PM           1720 README.md
------        3/10/2014   9:11 PM          65324 report.psm1
------        3/10/2014   9:11 PM          51921 scan.psm1

PS C:\Users\Carlos\Downloads\Posh-NVS-master> Import-Module -Verbose .\Posh-NVS.psd1
VERBOSE: Loading module from path 'C:\Users\Carlos\Downloads\Posh-NVS-master\Posh-NVS.psd1'.
VERBOSE: Loading 'Assembly' from path 'C:\Users\Carlos\Downloads\Posh-NVS-master\Assembly\nessus-sharp.dll'.
VERBOSE: Loading module from path 'C:\Users\Carlos\Downloads\Posh-NVS-master\scan.psm1'.
VERBOSE: Exporting function 'Show-NessusScans'.
VERBOSE: Exporting function 'Invoke-NessusScan'.
VERBOSE: Exporting function 'Stop-NessusScan'.
VERBOSE: Exporting function 'Resume-NessusScan'.
VERBOSE: Exporting function 'Suspend-NessusScan'.
VERBOSE: Exporting function 'Show-NessusScanTemplate'.
VERBOSE: Exporting function 'Invoke-NessusScanTemplate'.
VERBOSE: Exporting function 'New-NessusScanTemplate'.
VERBOSE: Exporting function 'Remove-NessusScanTemplate'.
VERBOSE: Exporting function 'Update-NessusScanTemplate'.
VERBOSE: Importing function 'Invoke-NessusScan'.
VERBOSE: Importing function 'Invoke-NessusScanTemplate'.
VERBOSE: Importing function 'New-NessusScanTemplate'.
VERBOSE: Importing function 'Remove-NessusScanTemplate'.

**Comment by darkoperator** [comment]
For 6 I started Posh-Nessus, still experimental at https://github.com/tenable/Posh-Nessus

**Comment by DigiAngel** [comment]
Thanks Carlos...I'm clearly not doming something right.  I'll give Posh-Nessus a go :)
